name: backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.11.0
  data_source:
    path: ../data_source
  dotenv: ^4.1.0
  either_dart: ^1.0.0
  exceptions:
    path: ../exceptions
  failures:
    path: ../failures
  models:
    path: ../models
  mongo_dart: ^0.9.1
  repository:
    path: ../repository
  typedefs:
    path: ../typedefs

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^5.0.0
